### ISSUE TITLE
MySQL: Too many connections

### ISSUE THREAD

**Issue by Dexus** [mrsimonemms/currencyjs#1]
```
objCurrency.convert(domains[i].currency, 'EUR', function(err, objConvert) {
                    if(err){
                        console.log('Error:',err);
                    } else {
                        objConvert.calculate(domains[i].setup);
                        domains_ext[i].setup = objConvert.getToValue();
                        objConvert.calculate(domains[i].unit);
                        domains_ext[i].unit = objConvert.getToValue();
                        // err should be null
                        // objConvert should be instance of Convert object
                    }
                });

```

OUTPUT:

```
Error: { [Error: ER_CON_COUNT_ERROR: Too many connections] code: 'ER_CON_COUNT_ERROR', fatal: true }
```

if i use this module within a foreach with more than 2 items than i get the error.

You need to release a connection befor you open a new connection.

**Comment by mrsimonemms** [comment]
Do you want to fork it and create a pull request?

**Comment by Dexus** [comment]
Sorry, i dont think that i have the time for it.

But i will try to find time to do.

**Comment by mrsimonemms** [comment]
I can't replicate this bug.  I did quite a bit of checking at this and have put a test in that cycles through all the currencies and gets the exchange rate.  As you can see from the [Travis output](https://travis-ci.org/riggerthegeek/currencyjs/builds/20872282), it works fine.  This test mocks out what you're doing above and can be found in _/test/integrationTest.js_ (line 657).

Also, if you check in the file _/lib/db/mysql/index.js_ (line 90), the _end()_ method is called after every query is made (even if it errors).

I suspect that this might be an issue with your MySQL setup rather than the package itself.
